### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Bots#1]
Привет. Посмотрел проект, есть то, что нужно исправить:

1. Заполнил конфиг для Телеграма, при запуске вижу следующее: `MrDestructoid: Logger with this name doesn't exist` .

2. В README должна быть описана архитектура проекта.

3. Я бы сказал, что у тебя через чур много уровней логирования. Info, Warning, Error должно вполне хватить.

4. В некоторых местах слишком большой уровень вложенности, например TelegramBot.Responder. Из-за этого код сложнее читать. Постарайся разбить функцию `handleCommandRepeat` и иметь максимум 2 уровня вложенности везде.

**Comment by DonDokidon** [comment]
Добрый день.
1. В коде действительно была ошибка, когда он пытался логировать ошибку до создания самого логера, что тут и написало, однако это случалось только в случае ошибки парсинга конфига, так что с твоей проблемой это напрямую не связано. Проверь свой конфиг, теперь, когда я пофиксил логи, найти ошибку не должно быть проблемой. Кроме того, тут телеграм и вк бот запускаются параллельно, соответственно если ты вбил данные для телеги, но не вбил данные для вк, то поток вк завершится с ошибкой, о чем лог и сообщит, а телега продолжит работать.
2. Можно пример как это должно выглядеть? просто <ModuleName> - <Описание> ?
3. Уровни логирования я скопировал с уже существующего и использующегося логера https://hackage.haskell.org/package/logger. Конечно в рамках тестовых заданий они не нужны, но если представить, что я собираюсь использовать и развивать свой логер в дальнейшем, то рано или поздно они понадобятся.
4. Не уверен что имеется в виду, там все функции задавались в let, сейчас я вынес их в where и вроде получилось 2 уровня.

**Comment by olegromashin** [comment]
>     2. Можно пример как это должно выглядеть? просто <ИмяМодуля> - <Описание> ?

Нет, просто можешь написать какой паттерн ты использовал, где посмотреть интерфейс и абстракции, где реализация, для чего нужны классы типов PFCastable, TextContainer, почему ты их ввёл, а не обошёлся встроенными средствами.
В общем представь, что это будет читать джуниор, который только-только освоился.


>     3. Уровни логирования я скопировал с уже существующего и использующегося логера

Есть такая штука, как минимальный полный функционал. Ты же делаешь не библиотеку, а конкретное приложение. Если в проекте есть какие-то штуки, которые тебе в данном проекте не нужны, но могут потребоваться в другом, то это очень неправильно.

**Comment by DonDokidon** [comment]
2. Как понял - написал
3. Удалил
