### ISSUE TITLE
Именование рекордов

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Bots#12]
Есть тип данных `Response` с полями `resp_update` и `resp_content`. Информация о типе данных в имени рекордов не нужна, т. к. ты используешь их только в контексте типа. Это создаёт лишний синтаксический шум. Надо просмотреть оба проекта на предмет таких недочётов.

**Comment by DonDokidon** [comment]
Что тогда мне делать с одинаковыми именами полей для разных сущностей? DuplicateRecordFields использовать как-то не хочется

**Comment by olegromashin** [comment]
Там, где надо избежать одинаковых имён можно указывать сущность, хотя ничего плохого в DuplicateRecordFields не вижу.

**Comment by DonDokidon** [comment]
Исправил
