### ISSUE TITLE
Поработать над читаемостью

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Bots#16]
На всём протяжении ревью твоих проектов я думаю как грамотно написать про читаемость, чтобы были конкретные примеры с твоим кодом, а не абстрактные советы. Сейчас напишу основные принципы, потом постараюсь выделить время на каких-то примерах твоего кода показать, как лучше его переписать, но попробуй сам со всем справится.
Вложенные друг в друга let-выражения, блоки where, иногда в связке с лямбда-функциями и кейсами, такой код очень тяжело воспринимать визуально, а пытаться вникнуть тем более. Надо подумать как отрефакторить.
Примеры: `logServerResponses`, `processCommandRepeat`, `repeatContent`.
Чего в идеале надо достичь:
1. Ни в одно let-выражение или блок where не встроено другое let-выражение или блок where.
2. Функции в do-нотации читаются как набор последовательных коротких шагов, соблюдён принцип единой ответственности. Например я бы вынес получение и обработку конфига из функции runVkBot и передавал в неё готовый конфиг. Потому что мы хотим запустить бота только когда у нас уже есть конфиг, ведь так? Я не смотрел насколько это возможно или удобно, просто пишу то, что бросается в глаза
3. Чистыя функции имеют высокоуровненую реализацию с понятными именами, а не сокращениями, лямда функции вынесены в отдельные функции или блоки where. Далее вынесенные функции уже могут содержать какую-то низкоуровненую реализацию в которой надо разбираться, если такая реализация читается сложно, то продолжить цепочку. Лично мне такое даётся сложнее всего, я потом постараюсь переделать какую-нибудь и привести пример.

**Comment by olegromashin** [comment]
На предмет таких же проблем надо просмотреть проект с сервером.

**Comment by olegromashin** [comment]
Добавление дублирующих имён со штрихами так же не очень хорошо воспринимается и часто неприветствуется. Приходится выяснять и держать в голове в чём разница. Но понятно, конечно, что иногда смысл переменных один и тот же.

**Comment by DonDokidon** [comment]
Ну по поводу вложенных let справедливо, но почему where? Неужели вынесение переменных и функций, которые использует только одна единственная функция из where, во внешний where (tryToSetRepeat как пример этого) лучше, чем инкапсулировать эти функции и переменные в where второго уровня? Или здесь шла речь именно про "монструозные" функции, коими были processCommandRepeat и logServerResponses?
run$Bot функции в моем представлении являются main функциями по своей сути. Если бы я не запускал их параллельно, то я бы просто писал main = runTelegramBot. В этом смысле чтение конфига находится именно там где ему следует быть - на самом внешнем уровне в инициализации всех нужных штук.
Функции со штрихами я использую по большей части как враперы для обычной функции, которые меняют только аргументы (func :: a -> b -> c -> d || func' :: (a, b, c) -> d например) и ничего дополнительного не делают. Поэтому имхо давать им другое имя не только трудно, но и вредно (будет казаться, что это какая-то другая функция с другим функционалом и пока не посмотришь - не узнаешь). Единственная альтернатива тут - циферки вместо штрихов... ну такое :) 
Сервер по большей части был достаточно прямолинеен, там мало что исправил

**Comment by olegromashin** [comment]
По поводу вложенных where: в принципе ничего плохо в инкапсуляции, просто часто из-за этого код сложнее читать, а это признак того, что что-то не так.
Функции со штрихами холиварная тема, я просто написал как принято у нас) Мы стараемся так вообще не делать. У тебя вроде это не мешает, так что ок.
С run-функциями не согласен. Логику твою я понял, но всё же считаю, что чтение конфига и запуск чего-либо это отдельные шаги. Например, если тебе надо выбирать из конфига что конкретно запускать, то ты явно будешь делать это уровнем выше. Здесь, конечно, кейс немного другой, но я просто на этом примере пояснил. Как считаешь?
Не закрывай ишью, я ещё поресёрчу проект.

**Comment by DonDokidon** [comment]
Если бы следовало реализовать выбор, я бы просто лишний раз прочел конфиг снаружи, все равно это происходит единожды при старте программы, дравбэк минимальный. Я просто предпочитаю делать части программы максимально обособленными - вызвал run, и код сам делает все что ему нужно, именно поэтому я так не хотел избавляться от unsafePerformIO. Наверное, меня ООП до сих пор не отпускает :) 
Энивей, сделал как ты сказал.

**Comment by olegromashin** [comment]
Внутри `buildResponses` есть функция `buildResponsesInternals`, которая состоит из одной строки со свёрткой. Думаю нет смысла её выносить, когда читаешь функцию всё равно приходится разбираться что такое `buildResponsesInternals`.

**Comment by DonDokidon** [comment]
все blablablaInternals  функции у меня делают то, что заявляла основная функция. Т.е в случае с buildResponsesInternals она именно конструирует респонсы, а основная делает доп работу в виде логирования и получения/сохранения стейта. Ну т.е если это понимать, то разбираться что это такое не приходится. Но исправил.

**Comment by DonDokidon** [comment]
Исправил buildResponse функцию
