### ISSUE TITLE
Тип данных Response

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Bots#17]
Можешь пояснить, почему тип `Response` содержит 2 поля типа `Content`? Одно, понятно, как собственное поле, а второе внутри `Message`, внутри `Update`.

**Comment by DonDokidon** [comment]
Потому что это 2 разных контента. Собственный - тот, которым мы отвечаем, а внутри Update - тот, что мы получили от юзера. Например при отправлении юзером "/repeat 2", контент внутри Update будет  `Text "/repeat 2"`
, а в респонсе будет что-то вроде ` Text "Новое значение для повторений установлено: 2"` 
Конечно не обязательно в респонс тащить прям всю полученную от юзера иформацию, но мне кажется так лучше - на вот этот запрос у нас вот такой ответ.

**Comment by olegromashin** [comment]
Хмм. Ну это явно избыточно, но сослаться на какой-то технический принцип я не могу, вместо того, чтобы просто написать, что это нелогично)
Давай рассмотрим наш конкретный случай: ты по сути передаёшь мессенджеру информацию о логике работы своего бота. Вряд ли она ему нужна и вообще когда-либо может понадобиться)

**Comment by DonDokidon** [comment]
Ну как минимум задача этого контента - отображаться в логах.
Не очень понимаю какую инфу о логике работы я передаю мессенджеру (насколько я понимаю ты имеешь в виду функцию отправки, а не сам телеграм :) ). По сути я просто оборачиваю то, что получено через getUpdates функцию и "информацией о логике" можно назвать разве что поле respContent, ведь только оно будет варьироваться в зависимости от нашей реализации. Ну и оно естественно не избыточно, вся суть работы бота в получении этого поля по сути.
Ну я конечно могу заставить Responder вычленять из апдейта только необходимую для ответа инфу, но это лишь добавит лишние функции по получению этой инфы и ничего толком не упростит и удобным не сделает.
Если предположить, что у бота будет дописываться функционал, и нам понадобится, например, поле messageId для ответа, то в моем случае изменится только модуль API, а в твоем придется дататайп менять и в респондере новые данные опять же вычленять и цеплять.
Избыточные данные не есть хорошо, но в данном случае мы изначально получаем контейнер со всеми нужными и ненужными данными, постоянно вручную их обрубать только чтобы избавиться от избыточности мне кажется не очень удобным.
Как-то так. Если не убедил - скажи, сделаю как ты сказал :)

**Comment by olegromashin** [comment]
Я не посмотрел, что ты отправляешь только один контент в итоге. я думал всё, сорян)
Но всё равно немного неправильно. С логами может конечно удобнее, но это не причина
Response - это ответ, который ты отправляешь юзеру на его сообщение. Я думаю любой, кто увидит тип Response подумает, что там то, чем мы отвечаем, а не исходное сообщение+ответ. Тогда уже называть это надо Conversation или как-то так.

> Если не убедил - скажи, сделаю как ты сказал :)

Ну не, если ты не согласен, то давай спорить)
