### ISSUE TITLE
Переименовать handleEvent

### ISSUE THREAD

**Issue by catdarick** [DonDokidon/Bots#3]
Название функции не соответствует её реализации. Функция не обрабатывает какое-то переданное событие, как следует из названия, а в цикле (рекурсии) получает их набор и затем обрабатывает. Стоит придумать другое название, также можно добавить в него `loop` или `infinite`, чтобы было понятно, что функция с вечной рекурсией. 
https://github.com/DonDokidon/Bots/blob/f923dbc226ecaf35089fd30062bdd95039f38063/src/TelegramBot/Runner.hs#L47

Названия важны, и код должен читаться так, чтобы не нужно было заглядывать в реализацию функции для того, чтобы понять её смысл.

**Comment by DonDokidon** [comment]
Под handleEvent подразумевалось "обработать событие запуска бота", но вне контекста, наверное, действительно непонятно. Переименовал в startListeningForUpdates, думаю достаточно четко обозначает намерения функции
