### ISSUE TITLE
Избавиться от непонятных сокращений

### ISSUE THREAD

**Issue by catdarick** [DonDokidon/Bots#4]
Не стоит использовать сокращения без необходимости, если они не общеприняты, как `req` (`request`) или `resp` (`response`). 
Названия `requests` и `requestsNumber` вполне неплохи 
https://github.com/DonDokidon/Bots/blob/f923dbc226ecaf35089fd30062bdd95039f38063/src/TelegramBot/Runner.hs#L58

**Comment by DonDokidon** [comment]
Возможно где-то пропустил, но основную часть исправил
