### ISSUE TITLE
Конфиг не должен быть изменяемым

### ISSUE THREAD

**Issue by catdarick** [DonDokidon/Bots#5]
Конфиг не должен быть изменяемым, он должен содержать исключительно константные значения. Настройки юзеров не должны быть внутри этого дататайпа.
Я бы предложил что-то наподобие:
```
data BotState = BotState
    { config       :: BotConfig
    , userSettings :: HM.HashMap ChatId Repeat
    }
```
Также стоит придерживаться одного стиля именования и функций, и полей в типах (`snake_case` и `camelCase`) . 
https://github.com/DonDokidon/Bots/blob/f923dbc226ecaf35089fd30062bdd95039f38063/src/TelegramBot/BotConfig.hs#L36

**Comment by DonDokidon** [comment]
Сделано
