### ISSUE TITLE
Переименовать handleRequests

### ISSUE THREAD

**Issue by catdarick** [DonDokidon/Bots#6]
`handle` обычно подразумевает под собой какое-то оконченное действие, то есть в случае `handleRequests` ожидается формирование ответа и его отправка. Но в коде эта функция ответы только формирует, поэтому стоит назвать её иначе, например `buildReponses`.
https://github.com/DonDokidon/Bots/blob/f923dbc226ecaf35089fd30062bdd95039f38063/src/TelegramBot/Runner.hs#L70

**Comment by DonDokidon** [comment]
Сделано
