### ISSUE TITLE
Переименовать Request

### ISSUE THREAD

**Issue by catdarick** [DonDokidon/Bots#7]
Стоит придерживаться терминологии API, имя `Request` (оно также не совсем подходит по смыслу)  можно переименовать в `Updates`: оно общее и для VK, и для TG.
https://github.com/DonDokidon/Bots/blob/f923dbc226ecaf35089fd30062bdd95039f38063/src/TelegramBot/API/DataTypes.hs#L120

**Comment by DonDokidon** [comment]
Сделано
