### ISSUE TITLE
Корректное завершение при ошибке вместо вечного ожидания

### ISSUE THREAD

**Issue by vladwix** [DonDokidon/Bots#8]
Сейчас если оба треда падают (`runTelegramBot` и `runVkBot`), то процесс не завершается, ожидая ввода `0` от пользователя. Ожидать ввода от пользователя впринципе не стоит, потому что при удаленном запуске (на реальном сервере) это выльется в проблемы.
Можно сделать через `Control.Concurrent.Async.concurrently`, например.

**Comment by DonDokidon** [comment]
Исправлено
