### ISSUE TITLE
unsafePerformIO

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Bots#9]
В очень редких случаях использование unsafePerformIO это лучший вариант. Сейчас у тебя теряется свойство ссылочной прозрачности, может быть ты и можешь предсказать поведение сейчас, но в других проектах это может вылиться  проблемы. Лучше, например, использовать окружение.

**Comment by DonDokidon** [comment]
Ну это понятно, что язык не предназначен для действий с unsafePerformIO, и лучше всего использовать его никогда, но в случае с логером-то зачем переносить в State сущность, которая с проектом по сути не связана, и таскать ее с собой во все функции? Опять же подход я скопировал с другого логера

**Comment by olegromashin** [comment]
Ну сущность просто не связана с логикой, а с проектом она связана напрямую. Здесь стоит подумать а нужна ли она вообще. Я думаю здесь правильнее брать id сообщения из json'а и логировать его вместо ведения своих. Ты же всё-таки клиент, который работает с конкретными сообщениями от сервера, а не сервер, который передаёт эти сообщения.

**Comment by DonDokidon** [comment]
Исправил. (Но мне это не нравится, пользоваться логером теперь не так удобно)
